# rtg_bev_msgs — ROS1 custom message package
# This package provides Python stubs for development environments without ROS1.
#
# When ROS1/rospy is available, these message types are auto-generated by
# the ROS1 build system (catkin_make) from the .msg files in the msg/ directory.
#
# The stubs below allow development and unit testing of postprocessing modules
# without a full ROS1 installation.

import collections


# ---------------------------------------------------------------------------
# Named constants matching the .msg field values
# ---------------------------------------------------------------------------

class ClassID:
    PERSON = 0
    TRUCK = 1
    CAR = 2
    OTHER_OBSTACLE = 3

    _names = {0: 'person', 1: 'truck', 2: 'car', 3: 'other_obstacle'}

    @classmethod
    def name(cls, class_id):
        return cls._names.get(class_id, 'unknown')


class TrackState:
    CANDIDATE = 0
    CONFIRMED = 1
    LOST = 2


class WarningLevel:
    NONE = 0
    INFO = 1
    WARNING = 2
    DANGER = 3


class EgoMotionStateEnum:
    STATIC = 0
    MOVING_PLUS_X = 1
    MOVING_MINUS_X = 2
    UNKNOWN = 3


# ---------------------------------------------------------------------------
# Lightweight stub classes for environments without ROS1
# ---------------------------------------------------------------------------

class _StubBase:
    """Base class for ROS1 msg stubs that supports attribute access."""

    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

    def __repr__(self):
        attrs = ', '.join(f'{k}={v!r}' for k, v in self.__dict__.items())
        return f'{self.__class__.__name__}({attrs})'


class Header(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if not hasattr(self, 'stamp'):
            self.stamp = None
        if not hasattr(self, 'frame_id'):
            self.frame_id = ''
        if not hasattr(self, 'seq'):
            self.seq = 0


class Detection(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        defaults = {
            'id': 0, 'class_id': 0, 'class_name': '',
            'confidence': 0.0, 'x': 0.0, 'y': 0.0, 'z': 0.0,
            'w': 0.0, 'l': 0.0, 'h': 0.0, 'yaw': 0.0,
            'vx': 0.0, 'vy': 0.0, 'distance': 0.0,
        }
        for k, v in defaults.items():
            if not hasattr(self, k):
                setattr(self, k, v)


class DetectionArray(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if not hasattr(self, 'header'):
            self.header = Header()
        if not hasattr(self, 'detections'):
            self.detections = []


class Track(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        defaults = {
            'track_id': 0, 'class_id': 0, 'age': 0,
            'x': 0.0, 'y': 0.0, 'z': 0.0,
            'vx': 0.0, 'vy': 0.0,
            'w': 0.0, 'l': 0.0, 'h': 0.0, 'yaw': 0.0,
            'state': TrackState.CANDIDATE,
        }
        for k, v in defaults.items():
            if not hasattr(self, k):
                setattr(self, k, v)


class TrackArray(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if not hasattr(self, 'header'):
            self.header = Header()
        if not hasattr(self, 'tracks'):
            self.tracks = []


class Warning(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        defaults = {
            'track_id': 0, 'warning_level': WarningLevel.NONE,
            'target_class': 0, 'distance': 0.0,
            'zone': '', 'trigger_reason': '',
            'trigger_time': None,
        }
        for k, v in defaults.items():
            if not hasattr(self, k):
                setattr(self, k, v)


class WarningArray(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if not hasattr(self, 'header'):
            self.header = Header()
        if not hasattr(self, 'warnings'):
            self.warnings = []
        if not hasattr(self, 'ego_motion_state'):
            self.ego_motion_state = EgoMotionStateEnum.UNKNOWN
        if not hasattr(self, 'active_zones'):
            self.active_zones = []


class WarningZone(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        defaults = {
            'name': '', 'weight': 0.0,
            'y_min': 0.0, 'y_max': 0.0,
            'description': '',
        }
        for k, v in defaults.items():
            if not hasattr(self, k):
                setattr(self, k, v)


class EgoMotionState(_StubBase):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        defaults = {
            'state': EgoMotionStateEnum.UNKNOWN,
            'confidence': 0.0,
            'displacement': 0.0,
            'velocity_estimate': 0.0,
        }
        for k, v in defaults.items():
            if not hasattr(self, k):
                setattr(self, k, v)
